import Head from 'next/head'
import axios from 'axios';

export default function Home() {
  const uploadFile = async(e: any) => {
    const file = e.target.files[0];
    const filename = encodeURIComponent(file.name);

    const res = await fetch(`/api/upload?file=${filename}`);

    const { url, fields } = await res.json();

    const formData = new FormData();
    Object.entries({ ...fields, file }).forEach(([key, value]) => {
      //@ts-expect-error value cannot be unknown
      formData.append(key, value);
    });
    try{
      const upload = await axios.post(url, formData);
      if (upload.status === 204) {
        console.log('Uploaded successfully!');
      } else {
        console.error('Upload failed.');
      }
    } catch (e) {
      console.log(e);
    }
  };
  return (
    <>
      <Head>
        <title>Gcloud Bucket Uploader</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <p>Upload file to Gcloud</p>
          <input
        onChange={uploadFile}
        type="file"
      />
        </div>
      </main>
    </>
  )
}
